### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by kd0vsw** [sailcut/sailcut#1]
Process:               sailcut [18762]
Path:                  /Applications/sailcut.app/Contents/MacOS/sailcut
Identifier:            com.sailcut.Sailcut
Version:               ???
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           sailcut [18762]
User ID:               501

Date/Time:             2015-11-27 09:23:00.838 -0600
OS Version:            Mac OS X 10.11.1 (15B42)
Report Version:        11
Anonymous UUID:        44A128CA-EBCC-F133-44FA-2662081B6C84

Sleep/Wake UUID:       D214B586-4432-4A21-B0D2-5E8728F370A3

Time Awake Since Boot: 940000 seconds
Time Since Wake:       88000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/Applications/sailcut.app/Contents/Resources/lib

Dyld Error Message:
  Library not loaded: QtGui.framework/Versions/4/QtGui
  Referenced from: /Applications/sailcut.app/Contents/Resources/lib/QtOpenGL
  Reason: image not found

Binary Images:
0x8fede000 - 0x8ff125bf  dyld (360.17) <E08B9CA8-D557-32D5-8DDD-E0B563900367> /usr/lib/dyld
0x90f3d000 - 0x90f3efff  libSystem.B.dylib (1225.1.1) <92CA3288-0AF8-3926-B60A-1A61894AFDF6> /usr/lib/libSystem.B.dylib
0x93eaa000 - 0x93eb8ff3  com.apple.opengl (12.0.34 - 12.0.34) <EA15AA3A-06D0-3895-BAB8-15D3814FA677> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
0x94847000 - 0x94847fff  com.apple.Carbon (154 - 157) <30EAD78E-42E0-3877-8189-3CDBD6B69315> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
0x9588e000 - 0x96567ffb  com.apple.AppKit (6.9 - 1404.13) <5BEF518D-E9B8-3542-86A0-0DFFE78C0178> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
0x98838000 - 0x98846ff7  libz.1.dylib (60) <A80F1776-4F93-3982-8CF0-32B636511C5A> /usr/lib/libz.1.dylib
0x9b8c4000 - 0x9b8cbfff  com.apple.agl (3.3.1 - AGL-3.3.1) <404A5574-EDF7-3C19-B8AD-9FDC8789B43E> /System/Library/Frameworks/AGL.framework/Versions/A/AGL

Model: MacBookPro10,1, BootROM MBP101.00EE.B0A, 4 processors, Intel Core i7, 2.3 GHz, 8 GB, SMC 2.3f36
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Graphics: NVIDIA GeForce GT 650M, NVIDIA GeForce GT 650M, PCIe, 1024 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54333531533642465238432D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54333531533642465238432D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xEF), Broadcom BCM43xx 1.0 (7.21.94.29.1a4)
Bluetooth: Version 4.4.2f1 16391, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM256E, 251 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 23.4

**Comment by jlaine** [comment]
This looks like an old version of Sailcut CAD. Can you give the latest beta a try please?

**Comment by smejko1** [comment]
Am I the only one with sailcut crashing on windows 7 & 10, osx? using latest versions avalible on the website. Now I am working in sc version 1.2 on windows 7, working good for now.

**Comment by jlaine** [comment]
Am closing this issue as it originally referred to an old sailcut version, however @smejko1 I'd love a new issue with details of what library is missing in 1.4.0 beta 2 so I can fix it!
