### ISSUE TITLE
Issue with gaff and foot length macOS

### ISSUE THREAD

**Issue by abuitel** [sailcut/sailcut#10]
There seems to be an issue with version 1.4.1 on macOS: the gaff length and foot length are automatically reset to the luff length when the lengths of the first two exceed the length of the luff.

**Comment by xtractif** [comment]
I'm trying to create a lug sail but gaff and foot length revert to luff length?

**Comment by sailcuter** [comment]
That is correct, SailcutCAD was designed for sails with an aspect ratio > 2, meaning that gaff and boom are not longer than the luff. That the origin of you problem and it is hardwired in the software. There is in addition some software internal logic which check that the sum of the 4 sides length entered is compatible with a closed perimeter assuming initially that the gaff can be vertical. I know that that logic is not bullet proof for low aspect ratio sails but there is a way to avoid theses limitations by incrementing slowly the various lengths and adjusting the gaff angle. But you will never beat the length of boom and gaff limited to luff length.
