### ISSUE TITLE
Math bugfix in vector dotProduct

### ISSUE THREAD

**Issue by gregshay79** [sailcut/sailcut#11]
Hello sailors..  
In working with this code, came across a problem in the math library.
(I am still figuring out how to post a pull request!)
Regards,
Greg Shay

diff --git a/src/geocpp/vector.cpp b/src/geocpp/vector.cpp
index 770c34b..83ed616 100644
--- a/src/geocpp/vector.cpp
+++ b/src/geocpp/vector.cpp
@@ -69,7 +69,7 @@ CVector3d CVector3d::crossProduct(const CVector3d &v1, const CVector3d &v2)
  */
 real CVector3d::dotProduct(const CVector3d &v1, const CVector3d &v2)
 {
-    return v1.m_x * v2.m_x + v1.m_y * v2.m_y + v1.m_z * v1.m_z;
+    return v1.m_x * v2.m_x + v1.m_y * v2.m_y + v1.m_z * v2.m_z;
 }

**Comment by gregshay79** [comment]
Pull request for this, created.

**Comment by jlaine** [comment]
Thanks so much for your pull request, merged!
