### ISSUE TITLE
compile error: missing QT include in 3 files.

### ISSUE THREAD

**Issue by jwstolk** [sailcut/sailcut#15]
I fixed the first two compile errors by adding "#include \<QAction\>"
```
   ../../src/formhull.cpp:56:18: error: invalid use of incomplete type ‘class QAction’
   56 |     actionViewDef->setText( tr("&Dimensions") );
      |                  ^~

../../src/formrig.cpp: In member function ‘void CFormRig::languageChange()’:
../../src/formrig.cpp:58:18: error: invalid use of incomplete type ‘class QAction’
   58 |     actionViewDef->setText( tr("&Dimensions") );
      |                  ^~
```
And the third by adding "#include \<QButtonGroup\>"
```
   ../../src/formsaildef.cpp: In constructor ‘CFormSailDef::CFormSailDef(QWidget*, CSailDef*)’:
   ../../src/formsaildef.cpp:98:57: error: invalid use of incomplete type ‘class QButtonGroup’
   98 |     QButtonGroup *bgrpSailType = new QButtonGroup( this );
      |                                                         ^
```

There are also a lot of compiler warnings, for example about "operator=" implicitly being defined, possibly because some data is copied while using a reference would have been more suitable, but I don't have the C++ experience to really understand what is going on.

(QT5,  gcc 9.4.0, Ubuntu 20.04.4 LTS)

**Comment by jlaine** [comment]
Hi, thanks for this report! Would your consider submitting a pull request with your changes?

**Comment by jwstolk** [comment]
I used the tar.gz archive. I would like to setup git and an on-line repository to be able to create a pull request but that will take some time. (I'm looking at a way to export the sail surface as IGES NURBS-surface in addition to the current DXF mesh, and a colleague also found a way to crash the program which I have not yet looked into yet.)

**Comment by jwstolk** [comment]
The git clone already had the missing includes, so this issue can be closed.
At least I now should have github setup correctly.

**Comment by jlaine** [comment]
Alright, thanks for reporting back!

**Comment by jwstolk** [comment]
I also found the cause, I used the source link on sailcut.com, which links to v1.4.1.tar.gz instead of the sailcut-master.zip archive from github which compiles without errors.
